var tree = [["[Global Namespace]",,"",
                [["AbstractXoopsObject","AbstractXoopsObject.html","",
                [        ]],["EasyLex_SQLScanner","EasyLex_SQLScanner.html","",
                [        ]],["EasyLex_SQLToken","EasyLex_SQLToken.html","",
                [        ]],["Lenum_GroupRank","Lenum_GroupRank.html","",
                [        ]],["Lenum_ImageType","Lenum_ImageType.html","",
                [        ]],["Lenum_Status","Lenum_Status.html","",
                [        ]],["Lenum_WorkflowStatus","Lenum_WorkflowStatus.html","",
                [        ]],["ShadePlus_ServiceServer","ShadePlus_ServiceServer.html","",
                [        ]],["ShadePlus_SoapClient","ShadePlus_SoapClient.html"," < XCube_AbstractServiceClient",
                [        ]],["ShadeSoap_NusoapServer","ShadeSoap_NusoapServer.html"," < soap_server",
                [        ]],["XCube_AbstractArrayProperty","XCube_AbstractArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_AbstractPermissionProvider","XCube_AbstractPermissionProvider.html","",
                [        ]],["XCube_AbstractProperty","XCube_AbstractProperty.html"," < XCube_PropertyInterface",
                [        ]],["XCube_AbstractRequest","XCube_AbstractRequest.html","",
                [        ]],["XCube_AbstractServiceClient","XCube_AbstractServiceClient.html","",
                [        ]],["XCube_ActionFilter","XCube_ActionFilter.html","",
                [        ]],["XCube_ActionForm","XCube_ActionForm.html","",
                [        ]],["XCube_BoolArrayProperty","XCube_BoolArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_BoolProperty","XCube_BoolProperty.html"," < XCube_AbstractProperty",
                [        ]],["XCube_Controller","XCube_Controller.html","",
                [        ]],["XCube_Delegate","XCube_Delegate.html","",
                [        ]],["XCube_DelegateManager","XCube_DelegateManager.html","",
                [        ]],["XCube_DelegateUtils","XCube_DelegateUtils.html","",
                [        ]],["XCube_DependClassFactory","XCube_DependClassFactory.html","",
                [        ]],["XCube_EmailValidator","XCube_EmailValidator.html"," < XCube_Validator",
                [        ]],["XCube_ExtensionValidator","XCube_ExtensionValidator.html"," < XCube_Validator",
                [        ]],["XCube_FieldProperty","XCube_FieldProperty.html","",
                [        ]],["XCube_FileArrayProperty","XCube_FileArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_FileProperty","XCube_FileProperty.html"," < XCube_AbstractProperty",
                [        ]],["XCube_FloatArrayProperty","XCube_FloatArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_FloatProperty","XCube_FloatProperty.html"," < XCube_AbstractProperty",
                [        ]],["XCube_FormFile","XCube_FormFile.html","",
                [        ]],["XCube_FormImageFile","XCube_FormImageFile.html"," < XCube_FormFile",
                [        ]],["XCube_GenericArrayProperty","XCube_GenericArrayProperty.html"," < XCube_PropertyInterface",
                [        ]],["XCube_GenericRequest","XCube_GenericRequest.html"," < XCube_AbstractRequest",
                [        ]],["XCube_HttpContext","XCube_HttpContext.html","",
                [        ]],["XCube_HttpRequest","XCube_HttpRequest.html"," < XCube_AbstractRequest",
                [        ]],["XCube_Identity","XCube_Identity.html","",
                [        ]],["XCube_ImageFileArrayProperty","XCube_ImageFileArrayProperty.html"," < XCube_FileArrayProperty",
                [        ]],["XCube_ImageFileProperty","XCube_ImageFileProperty.html"," < XCube_FileProperty",
                [        ]],["XCube_IniHandler","XCube_IniHandler.html","",
                [        ]],["XCube_IntArrayProperty","XCube_IntArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_IntProperty","XCube_IntProperty.html"," < XCube_AbstractProperty",
                [        ]],["XCube_IntRangeValidator","XCube_IntRangeValidator.html"," < XCube_Validator",
                [        ]],["XCube_LanguageManager","XCube_LanguageManager.html","",
                [        ]],["XCube_MaskValidator","XCube_MaskValidator.html"," < XCube_Validator",
                [        ]],["XCube_MaxValidator","XCube_MaxValidator.html"," < XCube_Validator",
                [        ]],["XCube_MaxfilesizeValidator","XCube_MaxfilesizeValidator.html"," < XCube_Validator",
                [        ]],["XCube_MaxlengthValidator","XCube_MaxlengthValidator.html"," < XCube_Validator",
                [        ]],["XCube_MinValidator","XCube_MinValidator.html"," < XCube_Validator",
                [        ]],["XCube_MinlengthValidator","XCube_MinlengthValidator.html"," < XCube_Validator",
                [        ]],["XCube_Object","XCube_Object.html","",
                [        ]],["XCube_ObjectArray","XCube_ObjectArray.html","",
                [        ]],["XCube_ObjectExistValidator","XCube_ObjectExistValidator.html"," < XCube_Validator",
                [        ]],["XCube_PageNavigator","XCube_PageNavigator.html","",
                [        ]],["XCube_Permissions","XCube_Permissions.html","",
                [        ]],["XCube_Principal","XCube_Principal.html","",
                [        ]],["XCube_PropertyInterface","XCube_PropertyInterface.html","",
                [        ]],["XCube_Ref","XCube_Ref.html","",
                [        ]],["XCube_RenderCache","XCube_RenderCache.html","",
                [        ]],["XCube_RenderSystem","XCube_RenderSystem.html","",
                [        ]],["XCube_RenderTarget","XCube_RenderTarget.html","",
                [        ]],["XCube_RequiredValidator","XCube_RequiredValidator.html"," < XCube_Validator",
                [        ]],["XCube_Role","XCube_Role.html","",
                [        ]],["XCube_RoleManager","XCube_RoleManager.html","",
                [        ]],["XCube_Root","XCube_Root.html","",
                [        ]],["XCube_Service","XCube_Service.html","",
                [        ]],["XCube_ServiceClient","XCube_ServiceClient.html"," < XCube_AbstractServiceClient",
                [        ]],["XCube_ServiceManager","XCube_ServiceManager.html","",
                [        ]],["XCube_ServiceUtils","XCube_ServiceUtils.html","",
                [        ]],["XCube_Session","XCube_Session.html","",
                [        ]],["XCube_StringArrayProperty","XCube_StringArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_StringProperty","XCube_StringProperty.html"," < XCube_AbstractProperty",
                [        ]],["XCube_TextArrayProperty","XCube_TextArrayProperty.html"," < XCube_GenericArrayProperty",
                [        ]],["XCube_TextFilter","XCube_TextFilter.html","",
                [        ]],["XCube_TextProperty","XCube_TextProperty.html"," < XCube_AbstractProperty",
                [        ]],["XCube_Theme","XCube_Theme.html","",
                [        ]],["XCube_Utils","XCube_Utils.html","",
                [        ]],["XCube_Validator","XCube_Validator.html","",
                [        ]],["XMLSchema","XMLSchema.html"," < nusoap_xmlschema",
                [        ]],["XcoreBlock_module_linkHandler","XcoreBlock_module_linkHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreBlock_module_linkObject","XcoreBlock_module_linkObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreBlockctypeHandler","XcoreBlockctypeHandler.html"," < XoopsObjectHandler",
                [        ]],["XcoreBlockctypeObject","XcoreBlockctypeObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreColumnsideHandler","XcoreColumnsideHandler.html"," < XoopsObjectHandler",
                [        ]],["XcoreColumnsideObject","XcoreColumnsideObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreCommentHandler","XcoreCommentHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreCommentObject","XcoreCommentObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreCommentstatusHandler","XcoreCommentstatusHandler.html"," < XoopsObjectHandler",
                [        ]],["XcoreCommentstatusObject","XcoreCommentstatusObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreGroup_permissionHandler","XcoreGroup_permissionHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreGroup_permissionObject","XcoreGroup_permissionObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreImageHandler","XcoreImageHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreImageObject","XcoreImageObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreImagebodyHandler","XcoreImagebodyHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreImagebodyObject","XcoreImagebodyObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreImagecategoryHandler","XcoreImagecategoryHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreImagecategoryObject","XcoreImagecategoryObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreModuletplObject","XcoreModuletplObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreNewblocksHandler","XcoreNewblocksHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreNewblocksObject","XcoreNewblocksObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreNon_installation_moduleHandler","XcoreNon_installation_moduleHandler.html"," < XoopsObjectHandler",
                [        ]],["XcoreRender_DelegateFunctions","XcoreRender_DelegateFunctions.html","",
                [        ]],["XcoreSmilesHandler","XcoreSmilesHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreSmilesObject","XcoreSmilesObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreTheme","XcoreTheme.html","",
                [        ]],["XcoreThemeHandler","XcoreThemeHandler.html","",
                [        ]],["XcoreThemeObject","XcoreThemeObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreTplfileHandler","XcoreTplfileHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreTplfileObject","XcoreTplfileObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreTplsetHandler","XcoreTplsetHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreTplsetObject","XcoreTplsetObject.html"," < XoopsSimpleObject",
                [        ]],["XcoreTplsourceHandler","XcoreTplsourceHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["XcoreTplsourceObject","XcoreTplsourceObject.html"," < XoopsSimpleObject",
                [        ]],["Xcore_AbstractBlockProcedure","Xcore_AbstractBlockProcedure.html","",
                [        ]],["Xcore_AbstractCacheInformation","Xcore_AbstractCacheInformation.html","",
                [        ]],["Xcore_AbstractCategoryObject","Xcore_AbstractCategoryObject.html"," < XoopsSimpleObject",
                [        ]],["Xcore_AbstractClientObjectHandler","Xcore_AbstractClientObjectHandler.html"," < XoopsObjectGenericHandler",
                [        ]],["Xcore_AbstractCommentAdminEditForm","Xcore_AbstractCommentAdminEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_AbstractControllerStrategy","Xcore_AbstractControllerStrategy.html","",
                [        ]],["Xcore_AbstractDebugger","Xcore_AbstractDebugger.html","",
                [        ]],["Xcore_AbstractDeleteAction","Xcore_AbstractDeleteAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_AbstractEditAction","Xcore_AbstractEditAction.html"," < Xcore_Action",
                [        ]],["Xcore_AbstractFilterForm","Xcore_AbstractFilterForm.html","",
                [        ]],["Xcore_AbstractGroupObject","Xcore_AbstractGroupObject.html"," < XoopsSimpleObject",
                [        ]],["Xcore_AbstractImageObject","Xcore_AbstractImageObject.html"," < XoopsSimpleObject",
                [        ]],["Xcore_AbstractListAction","Xcore_AbstractListAction.html"," < Xcore_Action",
                [        ]],["Xcore_AbstractModinfoReader","Xcore_AbstractModinfoReader.html","",
                [        ]],["Xcore_AbstractModule","Xcore_AbstractModule.html","",
                [        ]],["Xcore_AbstractModuleInstallAction","Xcore_AbstractModuleInstallAction.html"," < Xcore_Action",
                [        ]],["Xcore_AbstractObject","Xcore_AbstractObject.html"," < XoopsSimpleObject",
                [        ]],["Xcore_AbstractPreferenceEditState","Xcore_AbstractPreferenceEditState.html","",
                [        ]],["Xcore_AbstractThemeRenderTarget","Xcore_AbstractThemeRenderTarget.html"," < XCube_RenderTarget",
                [        ]],["Xcore_ActSearchAction","Xcore_ActSearchAction.html"," < Xcore_Action",
                [        ]],["Xcore_Action","Xcore_Action.html","",
                [        ]],["Xcore_ActionForm","Xcore_ActionForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ActionFrame","Xcore_ActionFrame.html","",
                [        ]],["Xcore_ActionSearchArgs","Xcore_ActionSearchArgs.html","",
                [        ]],["Xcore_ActionSearchForm","Xcore_ActionSearchForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ActionSearchRecord","Xcore_ActionSearchRecord.html","",
                [        ]],["Xcore_AdminActionSearch","Xcore_AdminActionSearch.html"," < Xcore_AbstractBlockProcedure",
                [        ]],["Xcore_AdminControllerStrategy","Xcore_AdminControllerStrategy.html"," < Xcore_AbstractControllerStrategy",
                [        ]],["Xcore_AdminRenderSystem","Xcore_AdminRenderSystem.html"," < Xcore_RenderSystem",
                [        ]],["Xcore_AdminSideMenu","Xcore_AdminSideMenu.html"," < Xcore_AbstractBlockProcedure",
                [        ]],["Xcore_AdminSmarty","Xcore_AdminSmarty.html"," < Smarty",
                [        ]],["Xcore_AdminSystemCheckPlusPreload","Xcore_AdminSystemCheckPlusPreload.html"," < XCube_ActionFilter",
                [        ]],["Xcore_AnonymousIdentity","Xcore_AnonymousIdentity.html"," < XCube_Identity",
                [        ]],["Xcore_ApprovalCommentAdminEditForm","Xcore_ApprovalCommentAdminEditForm.html"," < Xcore_AbstractCommentAdminEditForm",
                [        ]],["Xcore_ArrayOfInt","Xcore_ArrayOfInt.html"," < XCube_ObjectArray",
                [        ]],["Xcore_ArrayOfString","Xcore_ArrayOfString.html"," < XCube_ObjectArray",
                [        ]],["Xcore_BackendAction","Xcore_BackendAction.html"," < Xcore_Action",
                [        ]],["Xcore_BlockCacheInformation","Xcore_BlockCacheInformation.html"," < Xcore_AbstractCacheInformation",
                [        ]],["Xcore_BlockEditAction","Xcore_BlockEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_BlockEditForm","Xcore_BlockEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_BlockFilterForm","Xcore_BlockFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_BlockInfoCollection","Xcore_BlockInfoCollection.html","",
                [        ]],["Xcore_BlockInformation","Xcore_BlockInformation.html","",
                [        ]],["Xcore_BlockInstallEditAction","Xcore_BlockInstallEditAction.html"," < Xcore_BlockEditAction",
                [        ]],["Xcore_BlockInstallEditForm","Xcore_BlockInstallEditForm.html"," < Xcore_BlockEditForm",
                [        ]],["Xcore_BlockInstallFilterForm","Xcore_BlockInstallFilterForm.html"," < Xcore_BlockFilterForm",
                [        ]],["Xcore_BlockInstallListAction","Xcore_BlockInstallListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_BlockListAction","Xcore_BlockListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_BlockListForm","Xcore_BlockListForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_BlockProcedure","Xcore_BlockProcedure.html"," < Xcore_AbstractBlockProcedure",
                [        ]],["Xcore_BlockProcedureAdapter","Xcore_BlockProcedureAdapter.html"," < Xcore_BlockProcedure",
                [        ]],["Xcore_BlockUninstallAction","Xcore_BlockUninstallAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_BlockUninstallForm","Xcore_BlockUninstallForm.html"," < Xcore_CustomBlockDeleteForm",
                [        ]],["Xcore_Cacheclear","Xcore_Cacheclear.html"," < XCube_ActionFilter",
                [        ]],["Xcore_CommentAdminDeleteForm","Xcore_CommentAdminDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_CommentDeleteAction","Xcore_CommentDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_CommentEditAction","Xcore_CommentEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_CommentEditForm","Xcore_CommentEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_CommentEditForm_Admin","Xcore_CommentEditForm_Admin.html"," < Xcore_CommentEditForm",
                [        ]],["Xcore_CommentFilterForm","Xcore_CommentFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_CommentListAction","Xcore_CommentListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_CommentListForm","Xcore_CommentListForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_CommentViewAction","Xcore_CommentViewAction.html"," < Xcore_Action",
                [        ]],["Xcore_Controller","Xcore_Controller.html"," < XCube_Controller",
                [        ]],["Xcore_Criteria","Xcore_Criteria.html","",
                [        ]],["Xcore_CustomBlockDeleteAction","Xcore_CustomBlockDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_CustomBlockDeleteForm","Xcore_CustomBlockDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_CustomBlockEditAction","Xcore_CustomBlockEditAction.html"," < Xcore_BlockEditAction",
                [        ]],["Xcore_CustomBlockEditForm","Xcore_CustomBlockEditForm.html"," < Xcore_BlockEditForm",
                [        ]],["Xcore_DebuggerManager","Xcore_DebuggerManager.html","",
                [        ]],["Xcore_DialogRenderTarget","Xcore_DialogRenderTarget.html"," < Xcore_AbstractThemeRenderTarget",
                [        ]],["Xcore_EventFunction","Xcore_EventFunction.html","",
                [        ]],["Xcore_GenericPrincipal","Xcore_GenericPrincipal.html"," < XCube_Principal",
                [        ]],["Xcore_HeaderScript","Xcore_HeaderScript.html","",
                [        ]],["Xcore_HelpAction","Xcore_HelpAction.html"," < Xcore_Action",
                [        ]],["Xcore_HelpSmarty","Xcore_HelpSmarty.html"," < Smarty",
                [        ]],["Xcore_HtaccessViewAction","Xcore_HtaccessViewAction.html"," < Xcore_Action",
                [        ]],["Xcore_HttpContext","Xcore_HttpContext.html"," < XCube_HttpContext",
                [        ]],["Xcore_IPbanningFilter","Xcore_IPbanningFilter.html"," < XCube_ActionFilter",
                [        ]],["Xcore_Identity","Xcore_Identity.html"," < XCube_Identity",
                [        ]],["Xcore_ImageAdminCreateForm","Xcore_ImageAdminCreateForm.html"," < Xcore_ImageUploadForm",
                [        ]],["Xcore_ImageAdminDeleteForm","Xcore_ImageAdminDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ImageAdminEditForm","Xcore_ImageAdminEditForm.html"," < Xcore_ImageAdminCreateForm",
                [        ]],["Xcore_ImageCreateAction","Xcore_ImageCreateAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_ImageDeleteAction","Xcore_ImageDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_ImageEditAction","Xcore_ImageEditAction.html"," < Xcore_ImageCreateAction",
                [        ]],["Xcore_ImageFilterForm","Xcore_ImageFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_ImageListAction","Xcore_ImageListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_ImageListForm","Xcore_ImageListForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ImageUploadAction","Xcore_ImageUploadAction.html"," < Xcore_ImageEditAction",
                [        ]],["Xcore_ImageUploadForm","Xcore_ImageUploadForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ImagecategoryAdminDeleteForm","Xcore_ImagecategoryAdminDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ImagecategoryAdminEditForm","Xcore_ImagecategoryAdminEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ImagecategoryAdminNewForm","Xcore_ImagecategoryAdminNewForm.html"," < Xcore_ImagecategoryAdminEditForm",
                [        ]],["Xcore_ImagecategoryDeleteAction","Xcore_ImagecategoryDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_ImagecategoryEditAction","Xcore_ImagecategoryEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_ImagecategoryFilterForm","Xcore_ImagecategoryFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_ImagecategoryListAction","Xcore_ImagecategoryListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_ImagecategoryListForm","Xcore_ImagecategoryListForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_IndexRedirector","Xcore_IndexRedirector.html"," < XCube_ActionFilter",
                [        ]],["Xcore_InstallListAction","Xcore_InstallListAction.html"," < Xcore_Action",
                [        ]],["Xcore_InstallWizardAction","Xcore_InstallWizardAction.html"," < Xcore_AbstractModuleInstallAction",
                [        ]],["Xcore_InstallWizardForm","Xcore_InstallWizardForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_LanguageManager","Xcore_LanguageManager.html"," < XCube_LanguageManager",
                [        ]],["Xcore_Mailer","Xcore_Mailer.html"," < PHPMailer",
                [        ]],["Xcore_MiscFriendAction","Xcore_MiscFriendAction.html"," < Xcore_Action",
                [        ]],["Xcore_MiscFriendForm","Xcore_MiscFriendForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_MiscSmiliesAction","Xcore_MiscSmiliesAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_MiscSslloginAction","Xcore_MiscSslloginAction.html"," < Xcore_Action",
                [        ]],["Xcore_ModinfoX2DBReader","Xcore_ModinfoX2DBReader.html"," < Xcore_AbstractModinfoReader",
                [        ]],["Xcore_ModinfoX2FileReader","Xcore_ModinfoX2FileReader.html"," < Xcore_AbstractModinfoReader",
                [        ]],["Xcore_Module","Xcore_Module.html"," < Xcore_ModuleAdapter",
                [        ]],["Xcore_ModuleAdapter","Xcore_ModuleAdapter.html"," < Xcore_AbstractModule",
                [        ]],["Xcore_ModuleCacheInformation","Xcore_ModuleCacheInformation.html"," < Xcore_AbstractCacheInformation",
                [        ]],["Xcore_ModuleEditAction","Xcore_ModuleEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_ModuleEditForm","Xcore_ModuleEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ModuleInfoAction","Xcore_ModuleInfoAction.html"," < Xcore_Action",
                [        ]],["Xcore_ModuleInstallAction","Xcore_ModuleInstallAction.html"," < Xcore_Action",
                [        ]],["Xcore_ModuleInstallForm","Xcore_ModuleInstallForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ModuleInstallLog","Xcore_ModuleInstallLog.html","",
                [        ]],["Xcore_ModuleInstallUtils","Xcore_ModuleInstallUtils.html","",
                [        ]],["Xcore_ModuleInstaller","Xcore_ModuleInstaller.html","",
                [        ]],["Xcore_ModuleListAction","Xcore_ModuleListAction.html"," < Xcore_Action",
                [        ]],["Xcore_ModuleListFilterForm","Xcore_ModuleListFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_ModuleListForm","Xcore_ModuleListForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ModulePhasedUpgrader","Xcore_ModulePhasedUpgrader.html","",
                [        ]],["Xcore_ModulePreferenceEditForm","Xcore_ModulePreferenceEditForm.html"," < Xcore_PreferenceEditForm",
                [        ]],["Xcore_ModulePreferenceEditState","Xcore_ModulePreferenceEditState.html"," < Xcore_AbstractPreferenceEditState",
                [        ]],["Xcore_ModuleUninstallAction","Xcore_ModuleUninstallAction.html"," < Xcore_Action",
                [        ]],["Xcore_ModuleUninstallForm","Xcore_ModuleUninstallForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ModuleUninstaller","Xcore_ModuleUninstaller.html","",
                [        ]],["Xcore_ModuleUpdateAction","Xcore_ModuleUpdateAction.html"," < Xcore_Action",
                [        ]],["Xcore_ModuleUpdateForm","Xcore_ModuleUpdateForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_ModuleUpdater","Xcore_ModuleUpdater.html"," < Xcore_ModulePhasedUpgrader",
                [        ]],["Xcore_MysqlDebugger","Xcore_MysqlDebugger.html"," < Xcore_AbstractDebugger",
                [        ]],["Xcore_NonDebugger","Xcore_NonDebugger.html"," < Xcore_AbstractDebugger",
                [        ]],["Xcore_NotifyCancelAction","Xcore_NotifyCancelAction.html"," < Xcore_Action",
                [        ]],["Xcore_NotifyDeleteAction","Xcore_NotifyDeleteAction.html"," < Xcore_Action",
                [        ]],["Xcore_NotifyDeleteForm","Xcore_NotifyDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_NotifyListAction","Xcore_NotifyListAction.html"," < Xcore_Action",
                [        ]],["Xcore_NuSoapLoader","Xcore_NuSoapLoader.html"," < XCube_ActionFilter",
                [        ]],["Xcore_PHPDebugger","Xcore_PHPDebugger.html"," < Xcore_AbstractDebugger",
                [        ]],["Xcore_PendingCommentAdminEditForm","Xcore_PendingCommentAdminEditForm.html"," < Xcore_AbstractCommentAdminEditForm",
                [        ]],["Xcore_PreferenceEditAction","Xcore_PreferenceEditAction.html"," < Xcore_Action",
                [        ]],["Xcore_PreferenceEditForm","Xcore_PreferenceEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_PreferenceEditState","Xcore_PreferenceEditState.html"," < Xcore_AbstractPreferenceEditState",
                [        ]],["Xcore_PreferenceInfoCollection","Xcore_PreferenceInfoCollection.html","",
                [        ]],["Xcore_PreferenceInformation","Xcore_PreferenceInformation.html","",
                [        ]],["Xcore_PreferenceListAction","Xcore_PreferenceListAction.html"," < Xcore_Action",
                [        ]],["Xcore_PreferenceOptionInfoCollection","Xcore_PreferenceOptionInfoCollection.html","",
                [        ]],["Xcore_PreferenceOptionInformation","Xcore_PreferenceOptionInformation.html","",
                [        ]],["Xcore_PublicControllerStrategy","Xcore_PublicControllerStrategy.html"," < Xcore_AbstractControllerStrategy",
                [        ]],["Xcore_RenderSystem","Xcore_RenderSystem.html"," < XCube_RenderSystem",
                [        ]],["Xcore_RenderTargetMain","Xcore_RenderTargetMain.html"," < XCube_RenderTarget",
                [        ]],["Xcore_ResourcedbUtils","Xcore_ResourcedbUtils.html","",
                [        ]],["Xcore_RoleManager","Xcore_RoleManager.html","",
                [        ]],["Xcore_SQLScanner","Xcore_SQLScanner.html"," < EasyLex_SQLScanner",
                [        ]],["Xcore_SearchAction","Xcore_SearchAction.html"," < Xcore_SearchResultsAction",
                [        ]],["Xcore_SearchItem","Xcore_SearchItem.html"," < XCube_Object",
                [        ]],["Xcore_SearchItemArray","Xcore_SearchItemArray.html"," < XCube_ObjectArray",
                [        ]],["Xcore_SearchModule","Xcore_SearchModule.html"," < XCube_Object",
                [        ]],["Xcore_SearchModuleArray","Xcore_SearchModuleArray.html"," < XCube_ObjectArray",
                [        ]],["Xcore_SearchModuleResult","Xcore_SearchModuleResult.html"," < XCube_Object",
                [        ]],["Xcore_SearchModuleResultArray","Xcore_SearchModuleResultArray.html"," < XCube_ObjectArray",
                [        ]],["Xcore_SearchResultsAction","Xcore_SearchResultsAction.html"," < Xcore_Action",
                [        ]],["Xcore_SearchResultsForm","Xcore_SearchResultsForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_SearchService","Xcore_SearchService.html"," < XCube_Service",
                [        ]],["Xcore_SearchShowallAction","Xcore_SearchShowallAction.html"," < Xcore_SearchResultsAction",
                [        ]],["Xcore_SearchShowallForm","Xcore_SearchShowallForm.html"," < Xcore_SearchResultsForm",
                [        ]],["Xcore_SearchShowallbyuserAction","Xcore_SearchShowallbyuserAction.html"," < Xcore_SearchShowallAction",
                [        ]],["Xcore_SearchShowallbyuserForm","Xcore_SearchShowallbyuserForm.html"," < Xcore_SearchShowallForm",
                [        ]],["Xcore_SearchUtils","Xcore_SearchUtils.html","",
                [        ]],["Xcore_SessionCallback","Xcore_SessionCallback.html"," < XCube_ActionFilter",
                [        ]],["Xcore_SiteClose","Xcore_SiteClose.html"," < XCube_ActionFilter",
                [        ]],["Xcore_SmartyDebugger","Xcore_SmartyDebugger.html"," < Xcore_AbstractDebugger",
                [        ]],["Xcore_SmilesAdminDeleteForm","Xcore_SmilesAdminDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_SmilesAdminEditForm","Xcore_SmilesAdminEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_SmilesDeleteAction","Xcore_SmilesDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_SmilesEditAction","Xcore_SmilesEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_SmilesFilterForm","Xcore_SmilesFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_SmilesListAction","Xcore_SmilesListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_SmilesListForm","Xcore_SmilesListForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_SmilesUploadAction","Xcore_SmilesUploadAction.html"," < Xcore_Action",
                [        ]],["Xcore_SmilesUploadForm","Xcore_SmilesUploadForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_StartupXoopsTpl","Xcore_StartupXoopsTpl.html"," < XCube_ActionFilter",
                [        ]],["Xcore_SystemModuleInstall","Xcore_SystemModuleInstall.html"," < XCube_ActionFilter",
                [        ]],["Xcore_TextFilter","Xcore_TextFilter.html"," < XCube_TextFilter",
                [        ]],["Xcore_TextareaEditor","Xcore_TextareaEditor.html"," < XCube_ActionFilter",
                [        ]],["Xcore_ThemeListAction","Xcore_ThemeListAction.html"," < Xcore_Action",
                [        ]],["Xcore_ThemeRenderTarget","Xcore_ThemeRenderTarget.html"," < Xcore_AbstractThemeRenderTarget",
                [        ]],["Xcore_ThemeSelect","Xcore_ThemeSelect.html"," < XCube_ActionFilter",
                [        ]],["Xcore_ThemeSelectForm","Xcore_ThemeSelectForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplfileAdminDeleteForm","Xcore_TplfileAdminDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplfileCloneAction","Xcore_TplfileCloneAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_TplfileCloneForm","Xcore_TplfileCloneForm.html"," < Xcore_TplfileEditForm",
                [        ]],["Xcore_TplfileDeleteAction","Xcore_TplfileDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_TplfileDownloadAction","Xcore_TplfileDownloadAction.html"," < Xcore_Action",
                [        ]],["Xcore_TplfileEditAction","Xcore_TplfileEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_TplfileEditForm","Xcore_TplfileEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplfileFilterForm","Xcore_TplfileFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_TplfileListAction","Xcore_TplfileListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_TplfileSetFilterForm","Xcore_TplfileSetFilterForm.html"," < Xcore_TplfileFilterForm",
                [        ]],["Xcore_TplfileUploadForm","Xcore_TplfileUploadForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplfileViewAction","Xcore_TplfileViewAction.html"," < Xcore_Action",
                [        ]],["Xcore_TplsetCloneAction","Xcore_TplsetCloneAction.html"," < Xcore_TplsetEditAction",
                [        ]],["Xcore_TplsetCloneForm","Xcore_TplsetCloneForm.html"," < Xcore_TplsetEditForm",
                [        ]],["Xcore_TplsetDeleteAction","Xcore_TplsetDeleteAction.html"," < Xcore_AbstractDeleteAction",
                [        ]],["Xcore_TplsetDeleteForm","Xcore_TplsetDeleteForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplsetDownloadAction","Xcore_TplsetDownloadAction.html"," < Xcore_Action",
                [        ]],["Xcore_TplsetEditAction","Xcore_TplsetEditAction.html"," < Xcore_AbstractEditAction",
                [        ]],["Xcore_TplsetEditForm","Xcore_TplsetEditForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplsetFilterForm","Xcore_TplsetFilterForm.html"," < Xcore_AbstractFilterForm",
                [        ]],["Xcore_TplsetListAction","Xcore_TplsetListAction.html"," < Xcore_AbstractListAction",
                [        ]],["Xcore_TplsetSelectForm","Xcore_TplsetSelectForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_TplsetUploadAction","Xcore_TplsetUploadAction.html"," < Xcore_Action",
                [        ]],["Xcore_TplsetUploadForm","Xcore_TplsetUploadForm.html"," < XCube_ActionForm",
                [        ]],["Xcore_Utils","Xcore_Utils.html","",
                [        ]],["Xcore_Waiting","Xcore_Waiting.html"," < XCube_ActionFilter",
                [        ]],["Xcore_XoopsTpl","Xcore_XoopsTpl.html"," < XoopsTpl",
                [        ]],["Xcore_iActivityClientDelegate","Xcore_iActivityClientDelegate.html","",
                [        ]],["Xcore_iActivityDelegate","Xcore_iActivityDelegate.html","",
                [        ]],["Xcore_iCategoryClientDelegate","Xcore_iCategoryClientDelegate.html","",
                [        ]],["Xcore_iCategoryDelegate","Xcore_iCategoryDelegate.html","",
                [        ]],["Xcore_iCommentClientDelegate","Xcore_iCommentClientDelegate.html","",
                [        ]],["Xcore_iCommentDelegate","Xcore_iCommentDelegate.html","",
                [        ]],["Xcore_iGroupClientDelegate","Xcore_iGroupClientDelegate.html","",
                [        ]],["Xcore_iGroupDelegate","Xcore_iGroupDelegate.html","",
                [        ]],["Xcore_iImageClientDelegate","Xcore_iImageClientDelegate.html","",
                [        ]],["Xcore_iImageDelegate","Xcore_iImageDelegate.html","",
                [        ]],["Xcore_iTagClientDelegate","Xcore_iTagClientDelegate.html","",
                [        ]],["Xcore_iTagDelegate","Xcore_iTagDelegate.html","",
                [        ]],["Xcore_iWorkflowClientDelegate","Xcore_iWorkflowClientDelegate.html","",
                [        ]],["Xcore_iWorkflowDelegate","Xcore_iWorkflowDelegate.html","",
                [        ]],["XoopsAvatar","XoopsAvatar.html"," < XoopsObject",
                [        ]],["XoopsAvatarHandler","XoopsAvatarHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsBlock","XoopsBlock.html"," < XoopsObject",
                [        ]],["XoopsBlockHandler","XoopsBlockHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsCachetime","XoopsCachetime.html"," < XoopsObject",
                [        ]],["XoopsCachetimeHandler","XoopsCachetimeHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsComment","XoopsComment.html"," < XoopsObject",
                [        ]],["XoopsCommentHandler","XoopsCommentHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsConfigCategory","XoopsConfigCategory.html"," < XoopsObject",
                [        ]],["XoopsConfigCategoryHandler","XoopsConfigCategoryHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsConfigHandler","XoopsConfigHandler.html","",
                [        ]],["XoopsConfigItem","XoopsConfigItem.html"," < XoopsObject",
                [        ]],["XoopsConfigItemHandler","XoopsConfigItemHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsConfigOption","XoopsConfigOption.html"," < XoopsObject",
                [        ]],["XoopsConfigOptionHandler","XoopsConfigOptionHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsGroup","XoopsGroup.html"," < XoopsObject",
                [        ]],["XoopsGroupHandler","XoopsGroupHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsGroupPerm","XoopsGroupPerm.html"," < XoopsObject",
                [        ]],["XoopsGroupPermHandler","XoopsGroupPermHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsGuestUser","XoopsGuestUser.html"," < XoopsUser",
                [        ]],["XoopsImage","XoopsImage.html"," < XoopsObject",
                [        ]],["XoopsImageHandler","XoopsImageHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsImagecategory","XoopsImagecategory.html"," < XoopsObject",
                [        ]],["XoopsImagecategoryHandler","XoopsImagecategoryHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsImageset","XoopsImageset.html"," < XoopsObject",
                [        ]],["XoopsImagesetHandler","XoopsImagesetHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsImagesetimg","XoopsImagesetimg.html"," < XoopsObject",
                [        ]],["XoopsImagesetimgHandler","XoopsImagesetimgHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsMemberHandler","XoopsMemberHandler.html","",
                [        ]],["XoopsMembership","XoopsMembership.html"," < XoopsObject",
                [        ]],["XoopsMembershipHandler","XoopsMembershipHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsModule","XoopsModule.html"," < XoopsObject",
                [        ]],["XoopsModuleHandler","XoopsModuleHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsNotification","XoopsNotification.html"," < XoopsObject",
                [        ]],["XoopsNotificationHandler","XoopsNotificationHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsObject","XoopsObject.html"," < AbstractXoopsObject",
                [        ]],["XoopsObjectGenericHandler","XoopsObjectGenericHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsObjectHandler","XoopsObjectHandler.html","",
                [        ]],["XoopsOnlineHandler","XoopsOnlineHandler.html","",
                [        ]],["XoopsPrivmessage","XoopsPrivmessage.html"," < XoopsObject",
                [        ]],["XoopsPrivmessageHandler","XoopsPrivmessageHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsSessionHandler","XoopsSessionHandler.html","",
                [        ]],["XoopsSimpleObject","XoopsSimpleObject.html"," < AbstractXoopsObject",
                [        ]],["XoopsSubjecticon","XoopsSubjecticon.html"," < XoopsObject",
                [        ]],["XoopsSubjecticonHandler","XoopsSubjecticonHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsTimezone","XoopsTimezone.html"," < XoopsObject",
                [        ]],["XoopsTimezoneHandler","XoopsTimezoneHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsTplfile","XoopsTplfile.html"," < XoopsObject",
                [        ]],["XoopsTplfileHandler","XoopsTplfileHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsTplset","XoopsTplset.html"," < XoopsObject",
                [        ]],["XoopsTplsetHandler","XoopsTplsetHandler.html"," < XoopsObjectHandler",
                [        ]],["XoopsUser","XoopsUser.html"," < XoopsObject",
                [        ]],["XoopsUserHandler","XoopsUserHandler.html"," < XoopsObjectHandler",
                [        ]],["nusoap_base","nusoap_base.html","",
                [        ]],["nusoap_client","nusoap_client.html"," < nusoap_base",
                [        ]],["nusoap_fault","nusoap_fault.html"," < nusoap_base",
                [        ]],["nusoap_parser","nusoap_parser.html"," < nusoap_base",
                [        ]],["nusoap_server","nusoap_server.html"," < nusoap_base",
                [        ]],["nusoap_xmlschema","nusoap_xmlschema.html"," < nusoap_base",
                [        ]],["protectorLE_Filter","protectorLE_Filter.html"," < XCube_ActionFilter",
                [        ]],["soap_fault","soap_fault.html"," < nusoap_fault",
                [        ]],["soap_parser","soap_parser.html"," < nusoap_parser",
                [        ]],["soap_server","soap_server.html"," < nusoap_server",
                [        ]],["soap_transport_http","soap_transport_http.html"," < nusoap_base",
                [        ]],["soapclient","soapclient.html"," < nusoap_client",
                [        ]],["soapval","soapval.html"," < nusoap_base",
                [        ]],["wsdl","wsdl.html"," < nusoap_base",
                [        ]]        ]]        ]

